### PR TITLE
Multiples fix

### PR DESCRIPTION
**Pull request by BlivionIaG**

### CODE REVIEW

**Comment by MrPotatoBobx** [comment]
please explain what is fixed 👍

**Comment by MrPotatoBobx** [comment]
ill be working on  a pr/issue template soon.

**Comment by BlivionIaG** [comment]
oh right i described it on the commits : 
Fixing missing imports in checks.py
Fixing get_win_gpu() function (missing args and return values)
Missing imports in out.py
fixed subprocess call (now the neofetch values are retrieved)
Fix neoftech install check loop
Move shell detection to the "non windows part" in testing.py

**Comment by Hyper-KVM** [comment]
Looks good to me.

**Pull request merged**
