### PR TITLE
Add snap support

### PR DESCRIPTION
**Pull request by TabulateJarl8**
I recently figured out how to use snaps, and saw that "Snap Support" was in the todo list, so I went ahead and did it. [Here](https://snapcraft.io/docs/releasing-to-the-snap-store) are instructions on how to publish it to the snap store, and feel free to change any metadata of the snap. The snap store can also automatically build and release the snap for you by connecting it to your GitHub account ([https://snapcraft.io/build](https://snapcraft.io/build)). Feel free to ask me any questions about the snapcraft.

### CODE REVIEW

**Comment by BlivionIaG** [comment]
Oh I just saw the pr rn, i'll look into it tomorrow

**Comment by BlivionIaG** [comment]
Well i just looked and it seams quite simple ^^.

**Review by BlivionIaG — COMMENTED** [review]
Seams alright to me, I'll do the store thing tomorrow around 10-11pm cet

**Comment by TabulateJarl8** [comment]
I forgot to mention, if you want to release a version to the beta channel, set `grade` to `devel` and when running the `snap upload` command, add the `--release=beta` argument.

**Pull request merged**
